name: Check Pull Request

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node 17
        uses: actions/setup-node@v1
        with:
          node-version: 17.x

      - name: Install dependencies
        run: npm ci

      - name: Set version
        run: |
          echo "PACKAGE_VERSION=$(npm run version:bump --silent)" >> $GITHUB_ENV

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Bump version
        run: |
          echo "$PACKAGE_VERSION"
          git config --global user.name "GitHub CD bot"
          git config --global user.email "github-cd-bot@users.noreply.github.com"
          npm version "${{ env.PACKAGE_VERSION }}" -m "[RELEASE] %s" --no-commit-hooks
          git add -A
          git push --follow-tags

      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "ipa-rest"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
