name: Check Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 17
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
      - run: npm ci
      - run: npm test
